# Generated by Django 4.1.7 on 2023-02-22 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('location_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(choices=[('Renter', 'Renter'), ('Vendor', 'Vendor')], default='Renter', max_length=25)),
                ('profile_pic', models.ImageField(default='media/profile_pic/default.jpg', upload_to='media/profile_pic')),
                ('licence_pic', models.ImageField(default=0, upload_to='media/licence_pic')),
                ('password', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=25)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagementSystem.add_location')),
            ],
        ),
    ]
