# Generated by Django 4.1.7 on 2023-05-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementSystem', '0002_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
