# Generated by Django 4.1.7 on 2023-02-24 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='VehiclesTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='VendorFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagementSystem.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='AddVehicles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('picture', models.ImageField(default='media/vehicles/default.jpg', upload_to='media/vehicles')),
                ('model', models.CharField(default=None, max_length=150)),
                ('color', models.CharField(default=None, max_length=50)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField(default=0)),
                ('no_of_seats', models.IntegerField()),
                ('gear', models.CharField(choices=[('Manual', 'Manual'), ('Auto', 'Auto')], default='Manual', max_length=25)),
                ('slug', models.SlugField(default=None, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=25)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorSystem.company_name')),
                ('fuel_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='VendorSystem.fuel_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagementSystem.customuser')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorSystem.vehiclestypes')),
            ],
        ),
    ]
