# Generated by Django 4.1.7 on 2023-02-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvehicles',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='addvehicles',
            name='vehicle_number',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
