# Generated by Django 4.1.7 on 2023-02-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VendorSystem', '0002_remove_addvehicles_discounted_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvehicles',
            name='vehicle_number',
        ),
    ]
