# Generated by Django 4.1.7 on 2023-02-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VendorSystem', '0003_remove_addvehicles_vehicle_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvehicles',
            name='price',
        ),
    ]
