# Generated by Django 4.1.7 on 2023-02-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorSystem', '0004_remove_addvehicles_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvehicles',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
