# Generated by Django 4.1.7 on 2023-02-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorSystem', '0005_addvehicles_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvehicles',
            name='vehicle_number',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
