# Generated by Django 4.1.7 on 2023-02-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VendorSystem', '0006_addvehicles_vehicle_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvehicles',
            name='vehicle_number',
        ),
    ]
