# Generated by Django 4.1.7 on 2023-03-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorSystem', '0007_remove_addvehicles_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvehicles',
            name='vehicle_number',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
