# Generated by Django 4.1.7 on 2023-03-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorSystem', '0008_addvehicles_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvehicles',
            name='vehicle_number',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
