# Generated by Django 4.1.7 on 2023-03-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VendorSystem', '0009_alter_addvehicles_vehicle_number'),
        ('UserManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserved_vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('reserve_choice', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=25)),
                ('pickup_address', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('pickup_date', models.DateField(default=None)),
                ('dropoff_date', models.DateField(default=None)),
                ('pickup_time', models.TimeField(default=None)),
                ('Payment_Choices', models.CharField(choices=[('Khalti', 'Khalti'), ('pay_on_cash', 'pay_on_cash'), ('no_payment', 'no_payment')], default=None, max_length=50)),
                ('Payment_amount', models.CharField(default=None, max_length=25)),
                ('reserved_date', models.DateTimeField(auto_now=True)),
                ('Payment_done', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=25)),
                ('renter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagementSystem.customuser')),
                ('reserved_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorSystem.addvehicles')),
            ],
        ),
    ]
