# Generated by Django 4.1.7 on 2023-03-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserved_vehicle',
            name='Payment_Choices',
            field=models.CharField(choices=[('Khalti', 'Khalti'), ('pay_on_cash', 'pay_on_cash')], default=None, max_length=50),
        ),
    ]
